### ISSUE TITLE
AttributeError: 'PluginCollection' object has no attribute 'move_to_end'

### ISSUE THREAD

**Issue by Lisandra-dev** [ultrabug/mkdocs-static-i18n#164]
Hello,
When I try to build my site, the build process returns `AttributeError: 'PluginCollection' object has no attribute 'move_to_end'`

My environment : 
- Python 3.11 and Python 3.8
- mkdocs==1.4.2
- mkdocs-material==8.5.11
- mkdocs-static-i18n==0.51
- mkdocs-awesome-pages-plugin==2.8.0

The error seems to be caused because the plugins configuration is before the mkdocs-awesome-pages.

**Comment by ultrabug** [comment]
Indeed, the `mkdocs.plugins.PluginCollection` changed from `OrderedDict` to `dict` since mkdocs>=1.4.

For the record, I'm still hesitating to bump this plugin's minimal requirement of mkdocs and take advantage of the plugins prioritization feature of mkdocs 1.4 (which would solve this issue as well).

Let me reflect on this...

**Comment by ultrabug** [comment]
version 0.52 is out
