### ISSUE TITLE
Compatibility with `autolinks` plugin 

### ISSUE THREAD

**Issue by Stanzilla** [ultrabug/mkdocs-static-i18n#20]
Plugin: https://github.com/midnightprioriem/mkdocs-autolinks-plugin

I'm testing with version 0.3.0 because the latest release is buggy for me.

So during build it will throw a duplicate file warning for every file that contains a link to a file that now has a multi language version. In my repo for example

```
WARNING -  Documentation file 'getting_started/community_content.fr.md' contains a link to 'getting_started/publishing.md' which is not found in the documentation files. 
WARNING -  Documentation file 'getting_started/editor_intro.fr.md' contains a link to 'getting_started/my_first_multiplayer_game.md' which is not found in the documentation files. 
WARNING -  Documentation file 'getting_started/my_first_multiplayer_game.fr.md' contains a link to 'getting_started/installing_core.md' which is not found in the documentation files. 
WARNING -  Documentation file 'getting_started/my_first_multiplayer_game.fr.md' contains a link to 'getting_started/publishing.md' which is not found in the documentation files. 
WARNING -  Documentation file 'getting_started/my_first_multiplayer_game.fr.md' contains a link to 'getting_started/publishing.md' which is not found in the documentation files. 
WARNING -  Documentation file 'getting_started/publishing.fr.md' contains a link to 'getting_started/publishing_checklist.md' which is not found in the documentation files. 
WARNING -  Documentation file 'getting_started/publishing.fr.md' contains a link to 'getting_started/publishing_checklist.md' which is not found in the documentation files. 
WARNING -  Documentation file 'getting_started/publishing_checklist.fr.md' contains a link to 'getting_started/publishing.md' which is not found in the documentation files. 
WARNING -  Documentation file 'getting_started/publishing_checklist.fr.md' contains a link to 'getting_started/publishing.md' which is not found in the documentation files. 
WARNING -  Documentation file 'getting_started/publishing_checklist.fr.md' contains a link to 'getting_started/publishing.md' which is not found in the documentation files. 
WARNING -  Documentation file 'getting_started/publishing_checklist.fr.md' contains a link to 'getting_started/community_content.md' which is not found in the documentation files. 
```

**Comment by ultrabug** [comment]
I'm not sure messing with the markdown sources is the job of this plugin tbh.

The proper way to handle this is that `.fr.md` files should link to their `.fr.md` counterparts if they exist. Then autolinks will do its own magic without complaning.

**Comment by Stanzilla** [comment]
Hrm but what when they don't exist yet? Or did you suggest that I file that as a request over there?

**Comment by ultrabug** [comment]
As far as I understand this, autolinks is not the one spouting those WARNING messages.

You're seeing this because when `mkdocs-static-i18n` builds a language specific version of your site it only considers and uses the `translated` versions of all pages if they exist (and fallback to their default one if not).

Let's take an example:

```
WARNING -  Documentation file 'getting_started/community_content.fr.md' contains a link to 'getting_started/publishing.md' which is not found in the documentation files. 
```

In the markdown of the `getting_started/community_content.fr.md` file, there is a link to the `getting_started/publishing.md` (default = en) page **BUT** there is a `getting_started/publishing.fr.md` that exists and that is thus used by the french version of your site.

So on the `fr` context of the build the `getting_started/publishing.md` does not exist as it has been replaced by its `getting_started/publishing.fr.md` translation.

Which means that you should update the markdown of `getting_started/community_content.fr.md` to link to `getting_started/publishing.fr.md` so that french pages link to each others when they exist.

Does that make sense?

**Comment by Stanzilla** [comment]
oh it does, thank you! Guess I was kinda expecting some magic happening there that is doing it for me, but I can just change it!

**Comment by Stanzilla** [comment]
I guess the other part is these

```
WARNING -  A relative path to 'tutorials/environment_art.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'tutorials/modeling_basics.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'tutorials/persistent_storage_tutorial.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'tutorials/scene_creation.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'tutorials/lua_basics_helloworld.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'tutorials/lua_basics_lightbulb.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'tutorials/lua_basics_manticoin.md' is included in the 'nav' configuration, which is not found in the documentation files 
``` 

any idea what triggers those?

**Comment by ultrabug** [comment]
I guess it's the same problem @Stanzilla ?

```
src/getting_started/my_first_multiplayer_game.md:[Publish a Game](publishing.md) | [Terrain Tutorial](environment_art.md) | [Basic Weapon Tutorial](weapons.md) | [Abilities Tutorial](abilities.md)
src/getting_started/my_first_multiplayer_game.fr.md:[Publish a Game](publishing.md) | [Terrain Tutorial](environment_art.md) | [Basic Weapon Tutorial](weapons.md) | [Abilities Tutorial](abilities.md)
```

**Comment by Stanzilla** [comment]
So I guess the problem is that not all pages have a .fr counterpart yet?

**Comment by ultrabug** [comment]
> So I guess the problem is that not all pages have a .fr counterpart yet?

No, it seems you still have fr pages pointing to non fr pages while those pages do exist.

What's your newest test branch?

**Comment by Stanzilla** [comment]
It's in dev now, https://github.com/ManticoreGamesInc/platform-documentation/tree/development

**Comment by ultrabug** [comment]
@Stanzilla the WARNING you experience are there because you have some non translated pages pointing to files that **do** have a translation...

For example : 

- `other_platforms/fortnite_creative.md` is not translated in French and contains a link to `getting_started/editor_intro.md`
- but `getting_started/editor_intro.md` has a translation as `getting_started/editor_intro.fr.md`

when the `fr` version is built it only takes the translated versions of every page into account so `getting_started/editor_intro.md` does not exist in this context since it has a translation...

does it make sense?

**Comment by Stanzilla** [comment]
hrm yeah it does, that means everything should still work then because the "fallback" files that are not translated do exist, yes?

**Comment by ultrabug** [comment]
No, they do not exist in the language specific context so that means that whenever a page is translated, anything linking to it should be too

**Comment by ultrabug** [comment]
@Stanzilla do you still want this issue open mate, can I be of help here still? thanks

**Comment by Stanzilla** [comment]
I think it's fine to close it! Thank you so much for your help!

**Comment by ultrabug** [comment]
Thanks for your positive comments and help in improving the plugin mate
