### ISSUE TITLE
[Enhancement] Language detector based on user region

### ISSUE THREAD

**Issue by MetalKnight56** [ultrabug/mkdocs-static-i18n#235]
So i was wondering if there was a way for you to implement dynamic localization detection, so if a user is lets say, in japan the plugin will detect their region and check if the wiki has available japanese translations. So instead of the user having to change their language each time, the plugin does that work for them, also allowing ppl that don't have that much knowledge on how these things work to notice that there are indeed translations for them.

**Comment by ultrabug** [comment]
Hello @MetalKnight56 ; I guess that's something an external JS library could do and I'm not sure that's this plugin should take that kind of responsibility tbh since we're about providing content localization capabilities.

Maybe ask this question to the theme you're using or simply find an external JS lib that could do that for you?
