### ISSUE TITLE
This plugin doesn't support blog in mkdocs materia

### ISSUE THREAD

**Issue by mendax1234** [ultrabug/mkdocs-static-i18n#236]
Blog plugin has been added to mkdocs material recently in beta version. However, l notice that this plugin doesn't support blog function. And the error is below:

```
INFO     -  Building documentation...
WARNING  -  mkdocs-material language switcher contextual link is not compatible with theme.features = navigation.instant
WARNING  -  Language 'zh' is not supported by lunr.js, not setting it in the 'plugins.search.lang' option
INFO     -  Cleaning site directory
WARNING  -  A relative path to 'blog/posts/hello-world.zh.md' is included in the 'nav' configuration, which is not found
            in the documentation files
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Scripts\mkdocs.exe\__main__.py", line 7, in <module>      
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__  
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main      
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1688, in invoke    
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke    
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke     
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\commands\serve.py", line 83, in serve
    builder(config)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\commands\serve.py", line 76, in builder
build
    nav = config.plugins.run_event('nav', nav, config=config, files=files)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\plugins.py", line 520, in run_event    
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\material\plugins\blog\plugin.py", line 299, in on_nav
    head.previous_page.next_page = tail.next_page
                                   ^^^^^^^^^^^^^^
AttributeError: 'Link' object has no attribute 'next_page'
```
Hope this bug can be fixed!

**Comment by ultrabug** [comment]
This one is going to be tricky to get working as the material/blog plugin does not offer many options to lure it into supporting multiple files per post.

At a first glance, supporting the material/blog plugin would require different techniques between suffix and folder i18n structures...

Friendly ping @squidfunk since [I see that you're working on improving this plugin](https://github.com/squidfunk/mkdocs-material-insiders/pull/64/files)

**Comment by squidfunk** [comment]
We're working on stabilizing the blog plugin at the advent of the 9.2 release, and will also tackle the problem that the PR you linked attempts to fix – better support with plugins that allow to manage navigation dynamically. Currently, the blog plugin requires an explicit `nav`. This requirement will be lifted before the 9.2 release, so it will should work with awesome pages and other plugins. I'm, however, not sure what would be necessary to allow for working with this plugin, as I'm not familar with the different modes it supports. If we can make the blog plugin easily compatible, we're happy to do so, but I'm not sure  what it would require. If you, @ultrabug, or somebody else would like to work on a PR that makes it compatible, without tying it to this plugin explicitly, we're happy to consider. However, we'd kindly ask you to wait until the 9.2 release, as the blog plugin will go through a major refactor in the light of MkDocs 1.5, as it makes managing generated files much, much easier ☺️

**Comment by ultrabug** [comment]
Absolutely okay to wait for 9.2 and the overall update of the plugin @squidfunk, thanks for your input.

I'll be glad to help and contribute what it takes to make it compatible with this plugin so that users will be able to get multilang blogs using both our projects!

**Comment by squidfunk** [comment]
Material for MkDocs 9.2 is out! The blog plugin was completely rewritten. I invite you to [study the source code](https://github.com/squidfunk/mkdocs-material/tree/master/src/plugins/blog), it's heavily documented and pretty self-explanatory. Each page generated and managed by the blog plugin receives a distinct type, i.e., `Post`, `View`, `Archive`, `Category` and so forth. Those types can be imported and checked against by third-party plugins, something like:

``` py
from material.plugins.blog.structure import Post, View

def on_page_markdown(self, markdown, *, page, config, files):

    # Handle blog post
    if isinstance(page, Post):
        pass

    # Handle generated views, i.e., blog index, archive and category pages
    elif isinstance(page, View):
        pass
```

The following event priorities were given, so that third-party plugins can alter behavior before the blog plugin picks them up:

- `on_files` – `@event_priority(-50)`
- `on_nav` – `@event_priority(-50)`
- `on_page_markdown` – `@event_priority(-50)`
- `on_page_context` – `@event_priority(-100)`

That being said, we're happy to improve interop if you encounter any issues.
