### ISSUE TITLE
url changes after update to v1

### ISSUE THREAD

**Issue by ChrisBlankDe** [ultrabug/mkdocs-static-i18n#247]
With v0 my site was reachable with 3 urls:
https://whatever.tld/index.html
https://whatever.tld/en/index.html
https://whatever.tld/fr/index.html

after the update to v1 only the urls exist:
https://whatever.tld/index.html
https://whatever.tld/fr/index.html

--> the folder of the default language was removed.
this may be good to save storage/render time/..., but due to automatized external links i am dependent on my site being accessible in the default language under /en/.

do you have any idea how i can get this solved with v1

**Comment by hhslepicka** [comment]
I am running into the same problem with the default language folder not being available anymore.

**Comment by ultrabug** [comment]
Hi

Indeed, SEO hates duplicate content and the default language path was causing the code to be more complex than it should.

The v1.0.0 rationale stipulated the removal of the default language path, I guess I should have made that more clear I'm sorry.

**Comment by hhslepicka** [comment]
@ultrabug thank you for all the great work on the v1.0.0. On my side, I managed to adjust my URLs, and all is good now. I should have paid more attention to the release notes.

**Comment by kamilkrzyskow** [comment]
Possible band-aid solution could be redirects:
- Either use a theme override and override the 404.html page with some JavaScript redirect event, when the 404 page loads with a path containing the `en/` default directory, redirect to a path with that directory prefix removed.
- Make use of the https://github.com/mkdocs/mkdocs-redirects plugin, together with a custom hook which would update the redirect mapping dict (instead of doing so manually). Create a redirect for each `/` link so that a corresponding `en/` link would point to the correct `/` link. As reference I've made some changes relating the redirects plugin in the past, but they weren't related to this specific scenario: 
Custom hook - https://github.com/mkdocs/mkdocs/discussions/3134
i18n 0.5.6 patch - https://github.com/kamilkrzyskow/i18n/commit/83e1fd63cccf4baa379bf4f2792d88c85ded516c

**Comment by ultrabug** [comment]
Thanks for sharing those options @kamilkrzyskow ; closing here
