### ISSUE TITLE
Search shows Korean/Chinese pages when using default english

### ISSUE THREAD

**Issue by alexjlockwood** [ultrabug/mkdocs-static-i18n#271]
I have a page https://rolloff.club that uses the translation plugin. I'm wondering if it is intended that the search bar will include the search results of other languages? I've read the docs and it's hard for me to understand if this is something that can be avoided, as I know there is a `reconfigure_search` option that is enabled by default, but maybe I have misunderstood the purpose of this option.

I'm currently using mkdocs 1.5.3, mkdocs-material 9.4.3 and the latest 1.1.0 version of your plugin.

Below is a screenshot of me trying to search for something in the search bar and having results from multiple languages show up (in this case I just want English results to show up while in English mode).

![Screenshot_20231008-140355](https://github.com/ultrabug/mkdocs-static-i18n/assets/1380747/c2f34565-0537-49ad-b076-eb3305163914)

**Comment by ultrabug** [comment]
Hello @alexjlockwood 

Unfortunately, the material theme (and others) have a static and unique search index path AFAIK.

This means that everything has to be on the same search engine index and that it's not possible to have a search bar contextualized only to the current language :(

**Comment by kamilkrzyskow** [comment]
Hi @alexjlockwood
you could create some extra JavaScript extension to filter the search results via a `window.MutationObserver`. 
We're doing so in our docs: https://gothic-modding-community.github.io/gmc/ 

https://github.com/Gothic-Modding-Community/gmc/blob/8e15b7922228dc961557c9f1570eba14ffb47e32/overrides/assets/javascripts/extra.js#L108-L109

https://github.com/Gothic-Modding-Community/gmc/blob/8e15b7922228dc961557c9f1570eba14ffb47e32/overrides/assets/javascripts/extra.js#L212-L297

I believe you could just copy the code over and it would work as is with the Material Theme.
It's been some time since I touched the code, so I'm not sure if there is any TODO edge case bug left to fix 😅 
The filter uses page URLs to compare the results and remove the results from a different language. So it should work with both suffix and directory i18n setups.
I guess it requires that a fallback to the default language is present.
Let me know if there is anything "buggy" with the behaviour and I'll look into it.

**Comment by alexjlockwood** [comment]
Thank you @kamilkrzyskow I'll try that out!

**Comment by alexjlockwood** [comment]
Thanks a lot @kamilkrzyskow, I've managed to implement a simplified version that filters out search results using your code! https://github.com/alexjlockwood/roll-off-club/commit/13b0435deab3a308696d3467bc40b4ae4fbb4bf4

I think your logic was a bit more advanced than what I needed (as I think I am able to just simply discard search results coming from other languages). I didn't notice any bugs though, seems to work fine!

I suppose the only thing I will need to watch out for is if the material theme style names change at some point, but seems like that's unlikely to happen.

Thanks again!

**Comment by kamilkrzyskow** [comment]
Oh, I didn't notice that the page is open source, otherwise I might've made a PR. Our logic, apart of removing, also assures that search results to the fallback won't change the page locale to the fallback and will keep the active locale (we have a info bar prompting for translations).
Nice work with the code rewrite, looks even clearer that our version. Though, I would appreciate some mention in the commit message or some code comment for me or the GMC docs ✌️

**Comment by alexjlockwood** [comment]
Sure no problem I added a comment linking to your code 😊
