### ISSUE TITLE
click the homepage (on logo), dosen't localtion

### ISSUE THREAD

**Issue by zimocode** [ultrabug/mkdocs-static-i18n#4]
for now, it switch to  http://127.0.0.1:8000

in my opinion, it should switch to http://127.0.0.1:8000/en/ or http://127.0.0.1:8000/fr/

**Comment by ultrabug** [comment]
Hi @zimocode 

As far as I know, this link is part of the `theme`; not the documentation content which this plugin is responsible for I'm afraid

To override this, one would need to set up an overriding partial on their own documentation structure

Would you be interested that I provide partials examples to achieve that maybe?

**Comment by ultrabug** [comment]
After thinking about it more I think I'm wrong and it can be done at build time since this link is derived from the `site_url` parameter

Now just a question to you: how would one get back to the non localized version of the website ? there will be no button any more for this.

That being said, I guess the expected behavior is indeed to link to the localized version home when browsing localized...

I'll fix that, thanks @zimocode !

**Comment by ultrabug** [comment]
Thanks again @zimocode this is available on 0.4

**Comment by zimocode** [comment]
Hi,

I'm just test the new version (v0.4), but it don't works .

maybe , you didn't get what i express?
