### ISSUE TITLE
nav ordering

### ISSUE THREAD

**Issue by nzlz** [ultrabug/mkdocs-static-i18n#9]
Hello @ultrabug ! First of all, thanks for putting effort here :) 

Is there a way to support multi-lang and still keep pages/folders at custom order? I cannot find a combination where this works. Note that i cannot list .md files directly as now i have multiple lang suffixed files (.en.md , .es.md), so standard `nav:` tag ordering wont work as it breaks the non default lang page access.

**Comment by ultrabug** [comment]
Hi @nzlz thanks for your kind words

The best would be to provide an example of file tree of the current output you have and the one you would expect please?

Also, this plugin is compatible with the mkdocs-awesome-pages-plugin which is smarter for ordering FYI

**Comment by nzlz** [comment]
I managed to make it work following your working example at https://github.com/ultrabug/ultrabug.fr

there are couple of concerns like the need of setting strict to false, which shows warnings, but not big deal i guess:

```
  - awesome-pages:
      strict: false
```

Also, it would be nice if somehow clicking on the other language would send you to the other language alternative page instead of root. But its a minor thing, thanks again :) (closing issue, feel free to comment or reopen)

**Comment by ultrabug** [comment]
> there are couple of concerns like the need of setting strict to false, which shows warnings, but not big deal i guess

Yep, so far based on how mkdocs handles the source path of files to page object mapping I couldn't think of a more intuitive option yet. I think that since I now know that upstream is welcoming I will somehow make time to fix this someday.

> Also, it would be nice if somehow clicking on the other language would send you to the other language alternative page instead of root.

You mean on the `theme_overrides` i18n template? If so, let's open another issue because I've had the same feeling but didn't know if I was alone thinking about this too?
